### ISSUE TITLE
ディスコに参加するの初期チャンネルの表示

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#10]
その他→ディスコに参加する

◯課題
初期表示として、Deleted Userのメッセージが表示される。
これは、アプリを初めて使ってDiscordに参加者には、一切関係ない情報である。

◯対応案
・Deleted Userの投稿を削除
・アプリ向けとして、R18用のゾーニングのロール付与のチャンネルを付与してほしい。
（極論を言えば、アプリ利用者がディスコに**参加しやすいフロー**と**雰囲気**を出してほしい）

**Comment by reiwa** [comment]
@nakatsuka-k 招待URLを変更すると解決する？

**Comment by nakatsuka-k** [comment]
調べましたが現象がよく分かりませんでした。

**Comment by nakatsuka-k** [comment]
取り合えずカスタム招待リンクをつくってみました。
https://discord.gg/aipictors

**Comment by haruharu-1105** [comment]
アプリからDiscordへのリンクが削除されたため　本件クローズ
