### ISSUE TITLE
フィード画面　フィード画面のいいねアイコンの色が更新されない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#105]
## どの機能に関する不具合ですか？

- [x] いいね

## どのような不具合が発生しましたか？

画面のいいねのアイコンが赤色に更新されない。
※数字は更新されています。

## どのような操作をしましたか？

1. 作品画面で「いいね」を行います。
1. フィード画面に戻ります。
1. フィード画面の「いいね」のアイコンが更新されません。【不具合】

[動画の20秒～](https://github.com/aipictors/app/assets/132221228/f4e0d2d1-484f-4548-af27-53203a8d9062)

## どの端末で確認しましたか？

- [x] Android

## 許せないですか？

- [x] 許せる

**Comment by Stella2211** [comment]
この状態でフィード画面からいいねを押すと、UI上はいいねを付けたという表示になるにも関わらず、内部的にはいいねの取り消し処理が行われてしまうようです。

**Comment by Stella2211** [comment]
修正しました！
https://github.com/aipictors/app/assets/104188098/d5bfd556-3414-4c80-a639-4ebfaac127e1

**Comment by haruharu-1105** [comment]
ありがとうございます。リリース後に確認致します。

**Comment by haruharu-1105** [comment]
修正を確認しました。対応ありがとうございます。
バージョン: 0.5.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT
