### ISSUE TITLE
作品にスタンプ投稿時「Unknown error occurred.」が発生します

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#112]
## どの機能に関する不具合ですか？

- [x] 投稿　他作品にスタンプ

## どのような不具合が発生しましたか？

作品にスタンプ投稿時「Unknown error occurred.」が発生します

## どのような操作をしましたか？

1. ログイン済み　かつ　アプリの言語設定を英語
1. 見つけるタブでキーワード検索「猫耳少女と図書館」を検索
1. 作品ID「59116」を表示
1. スタンプを投稿する。　
1. 1分後に、再度3を行った所、「Unknown error occurred.」が発生します【不具合】

https://github.com/aipictors/app/assets/132221228/f4e02e47-12f9-4de8-b96d-a0b87a9cebda

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.4.4, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

**Comment by Stella2211** [comment]
エラーメッセージが適切に表示されていないのですが、コメントの連投対策機能によってブロックされている可能性があります。

**Comment by Stella2211** [comment]
エラーメッセージが適切に表示されない問題、[こちら](https://github.com/aipictors/app/commit/3feff9445e100cf3390aa3b664bfb4f91bcfb98b)で修正されました。
