### ISSUE TITLE
作品画面でコメント未入力で、送信ボタンを押すと「不明なエラーが発生しました。」が表示される

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#118]
## どの機能に関する不具合ですか？

- [x] 投稿　作品画面で送信ボタン

## どのような不具合が発生しましたか？

作品画面でコメント未入力で、送信ボタンを押すと「不明なエラーが発生しました。」が表示される

## どのような操作をしましたか？

1. 作品画面を開き、コメント未入力状態で、送信をします。

https://github.com/aipictors/app/assets/132221228/8e1c490b-2e39-4c73-8f79-7a0d1759d59a

## どの端末で確認しましたか？

- [x] Android
バージョン: 0.4.4, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

**Comment by haruharu-1105** [comment]
追記
- 個人的に望ましい動作
コメントが未入力 or スタンプが未選択状態の場合、
→送信ボタンが押せなくなる。

https://github.com/aipictors/app/assets/132221228/90975f4e-86cc-4453-a25f-af5673342d85

**Comment by Stella2211** [comment]
[こちら](https://github.com/aipictors/app/commit/3feff9445e100cf3390aa3b664bfb4f91bcfb98b)で修正されました。
