### ISSUE TITLE
一部のユーザーIDでログインできない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#120]
## どの機能に関する不具合ですか？

- [x] ログイン

## どのような不具合が発生しましたか？

ログインできない可能性があるユーザーID
1, ユーザーIDにハイフンが含まれるユーザー
LINEから登録したユーザー or IDに‐をつけているユーザーです。
https://github.com/aipictors/app/blob/4598f7fe97672514d4b2491bfc070b4e1be84598/lib/widgets/form/login_id_form.dart#L24

2, ユーザーIDに英小文字がないユーザ－
例）ID名が英大文字と+αのユーザー
https://github.com/aipictors/app/blob/4598f7fe97672514d4b2491bfc070b4e1be84598/lib/widgets/form/login_id_form.dart#L40
![image](https://github.com/aipictors/app/assets/132221228/60aed75d-f247-4723-81a7-1e33230f4852)

## どのような操作をしましたか？

1. その他タブ→アカウント→「ログインIDの変更」
1. IDを変更する

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.5.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せない

**Comment by Stella2211** [comment]
対応しました。
![Screenshot_20231027-213608~2](https://github.com/aipictors/app/assets/104188098/f609cd19-551e-4c4c-8e3e-356a8ff48aaa)
![Screenshot_20231027-213810~2](https://github.com/aipictors/app/assets/104188098/2957a0ca-4f68-482f-a2be-2360e3b4293e)

**Comment by haruharu-1105** [comment]
【メモ】
ログイン時の文字数制限の件も確認する。

> update: ログイン画面の文字数制限を無くす
> https://github.com/aipictors/app/commit/1ddd429f2f845efa2a12ff1a18dd91e097ea5c4f
