### ISSUE TITLE
非ログイン時　ユーザー及び作品の通報が行えない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#127]
## どの機能に関する不具合ですか？

- [x] それ以外　報告機能

## どのような不具合が発生しましたか？

非ログイン時のユーザー及び作者の通報が通知されない。

## どのような操作をしましたか？

1. 作品画面より、ユーザーの報告と作品の報告を行いました。

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.5.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

※非ログイン時の通報機能は、アプリの機能要件かどうかは不明です。

**Comment by reiwa** [comment]
おそらく非ログイン時でも通報機能が必要です。

**Comment by Stella2211** [comment]
GraphQL側で対応しました。
