### ISSUE TITLE
キャッシュクリア時　キャッシュ削除量がホームタップ経由での削除よりも少ない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#128]
## どの機能に関する不具合ですか？

- [x] それ以外

## どのような不具合が発生しましたか？

- アプリ内のその他タブ→「キャッシュクリア」
- アプリ長押しのストレージ→「キャッシュを削除」

２つの値を見比べた時、削除されていない可能性があるキャッシュが存在します。

## どのような操作をしましたか？

1. アプリ内のその他タブ→「キャッシュクリア」（ユーザーデータが減少）
![image](https://github.com/aipictors/app/assets/132221228/e1aeef95-ca2b-4e69-b8a9-2ddf3d3bd8e4)
1. アプリ長押しのストレージ→「キャッシュを削除」（キャッシュが0に）
![image](https://github.com/aipictors/app/assets/132221228/c73591c2-94e9-450c-b48a-5688bab60d1f)

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.5.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

**Comment by Stella2211** [comment]
GraphQLキャッシュは削除されているものの、画像キャッシュが削除できていないように見えたので、削除するように変更しました。
しかし、まだどこかに少しキャッシュが残っているようで、0Bにはなりませんでした。
（動画のアイコンの色が違うのは気にしないでください。開発版とリリース版を区別するためのものです。）

https://github.com/aipictors/app/assets/104188098/76dc73fd-b632-4798-ada9-4d2f1ab817ff
