### ISSUE TITLE
非ログイン時　フォロー操作を行った時に、ログインを促すダイアログが表示されない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#130]
## どの機能に関する不具合ですか？

- [x] それ以外　フォロー

## どのような不具合が発生しましたか？

非ログイン時のフォロー操作時に、ログインを促すダイアログが表示されません。
![image](https://github.com/aipictors/app/assets/132221228/ea34f5ac-5800-41f5-848d-7439eadd7f9e)

## どのような操作をしましたか？

1. 非ログイン状態
1. 「ホーム」フィード→右上の「…」→ユーザをフォローする。

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.5.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

**Comment by Stella2211** [comment]
![スクリーンショット 2023-10-27 20 55 57](https://github.com/aipictors/app/assets/104188098/5352d211-e7b0-4ed4-b9d3-a6f76b2273dd)
対応しました。

**Comment by haruharu-1105** [comment]
ありがとうございます。リリース後に確認します。
