### ISSUE TITLE
非ログイン時　ミュートボタンが押せるが反応がない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#131]
## どのような問題がありますか？
非ログイン時にミュートボタンが押せるが反応がない。

- ホームフィードの「…」の「ユーザをミュートする」
- プロフィール画面の「…」の「ユーザをミュートする」

## どうすれば良いですか？
非ログイン時にミュート操作が行えないのでしたら、非表示に変更して欲しいです。

**Comment by Stella2211** [comment]
![スクリーンショット 2023-10-27 20 57 01](https://github.com/aipictors/app/assets/104188098/c3dd96b0-8dfd-48d3-8688-799e3b57e17b)
修正しました。
