### ISSUE TITLE
フィード画面にてスタンプを投稿時、画面のコメント件数が更新されない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#139]
## どの機能に関する不具合ですか？

- [x] フィード
　スタンプを投稿時にコメント数の欄が更新されない。
　
## どのような不具合が発生しましたか？

1. フィード画面のスタンプを投稿時にコメント件数が更新されない。
1. スタンプが選択状態にならない。

## どのような操作をしましたか？

https://github.com/aipictors/app/assets/132221228/3cd9a975-f088-4506-b07c-7d53de264303

1. フィード画面からスタンプを行いました。

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.5.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

**Comment by Stella2211** [comment]
修正しました。


https://github.com/aipictors/app/assets/104188098/a412adf8-b02c-48db-84a6-4feb07bfa0c5
