### ISSUE TITLE
フィード画面　いいね数の桁上り発生時、右横のシェアアイコンの位置がずれる。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#141]
## どのような問題がありますか？
- シェアアイコンの位置ズレ
いいね数が9から10に変わった時に、シェアアイコンの表示位置がズレます。

https://github.com/aipictors/app/assets/132221228/898eef80-50ef-439e-b6a3-06d9b9e14159

## どうすれば良いですか？
予め領域を取るなどして、ズレないようにして欲しいです。

**Comment by Stella2211** [comment]
あらかじめ3桁分の幅を確保し、ほとんどの場合でズレないよう修正しました。

https://github.com/aipictors/app/assets/104188098/342a5a9c-0955-4bf6-b7c0-c6a51f3132e6
