### ISSUE TITLE
広告判定された作品を除外する

### ISSUE THREAD

**Issue by mikageymir** [aipictors/app#142]
## どのような問題がありますか？

サイトではデフォルトで広告判定された規約違反作品が表示されないのに、
アプリでは表示されてしまう。

## どうすれば良いですか？

works.isHideExplanation が0なら通常、1なら広告判定なので、1の作品を除外する。
このフラグは10分に1回のバッチで更新されるので、0のときにデータをキャッシュしているなら何らかの更新処理が必要かも。

**Comment by reiwa** [comment]
@mikageymir 広告判定された作品が表示されることはない？マイページには表示される？

**Comment by nakatsuka-k** [comment]
マイページでは表示されます。

**Comment by reiwa** [comment]
APIに広告判定された作品を除外する機能を追加した。でもアプリのキャッシュには残ってしまう。
