### ISSUE TITLE
削除された通知の表示は違和感がある

### ISSUE THREAD

**Issue by nakatsuka-k** [aipictors/app#143]
## どのような問題がありますか？
削除された通知があることが表示されます。
サイトでは削除されたら跡形なく消えます。
いいねして取り消した場合とかだと思われるが違和感があります。
![IMG_8095](https://github.com/aipictors/app/assets/124619691/791a3f64-fe07-4304-8d4c-f87aa47491dd)

## どうすれば良いですか？
削除された通知は表示する必要がないと思われます。

**Comment by Stella2211** [comment]
修正しました。
削除された通知はGraphQL側でフィルタされており、表示されていませんでした。
しかし、定期いいね通知への適切な対応ができておらず、削除された通知として表示される問題がありました。
