### ISSUE TITLE
非ログイン時　ホームタブの「いいね」からログイン後、フォロータブと通知タブの内容が更新されない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#145]
## どの機能に関する不具合ですか？

- [x] ログイン

## どのような不具合が発生しましたか？

非ログイン時に「いいね」からログインを行うと、
- 「フォロー」タブと「通知」タブが、更新されません。
（ログインユーザーの内容で表示されて欲しいです。）
- ログイン画面がクローズしない。

## どのような操作をしましたか？

1. 非ログイン状態
1. ホームの作品を「いいね」→ログインを促すダイアログが表示され、ログインを行う。
1. 「ログインしました。」の表示がされるが、ログイン画面がクローズしない【不具合１】
1. その後、画面左上の「←」で戻る。この時、「フォロー」が再描画されない。【不具合２】
2. 同じく、通知タブの通知が再描画されない。【不具合２】

## どの端末で確認しましたか？

- [x] Android
　バージョン: 1.0.0, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せる

## 関連
フィード画面のいいねよりログイン時も発生する。
Special Thanks! Stella

**Comment by Stella2211** [comment]
ホームのログインタブではなく、ログイン画面(/login)からログインすると発生するようです。
そのため、`context.push('/login')`を、以下のように変更すればこの問題は発生しないのですが、この方法では、非ログイン時にいいねを押そうとした作品のページを閉じてしまうので、可能であれば他の方法で修正したいです。
```
Navigator.of(context).popUntil((route) => route.isFirst);
final notifier = ref.read(homeTabIndexProvider.notifier);
notifier.toLoginTab();
```

**Comment by Stella2211** [comment]
ホームのログインタブに飛ばす方法で解決することになりました。
