### ISSUE TITLE
お題のコメント欄を押しても反応しない。（非ログイン時）

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#28]
## どの機能に関する不具合ですか？

- [ ] それ以外
 下部のお題→8月19日　バイク→作品を選択後の画面

## どのような不具合が発生しましたか？

コメントボタンを押しても反応しません。
（非ログイン時）

## どのような操作をしましたか？

1. 画面右下のコメントボタンをタップ

## どの端末で確認しましたか？

- [ ] Android

## 許せないですか？

- [ ] 許せる

**Comment by Stella2211** [comment]
こちら、コメントボタンを押した際の動作がまだ実装されていないようです。
ログインしていても反応しませんでした。

**Comment by Stella2211** [comment]
UIの変更に伴い、すでに発生しなくなっているようです。
