### ISSUE TITLE
【フィード】長い投稿者名の場合、フォロー中の文字が重なる。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#85]
## どのような問題がありますか？

フィード→フォロータブで投稿者名が長い場合、と画像の用にフォロー中の文字と重なります。
![image](https://github.com/aipictors/app/assets/132221228/5d6ad242-69b6-4693-84fa-ca3449a514f4)

## どうすれば良いですか？
案１：フォロー中の文字を非表示にする。
（横のボタンで操作できるため）
　デメリット：ワンクッションアクションが増える。
案２：アイコンにする。

案３：フォロータブの表示時は、TLに出るのはフォロー中なのは自明なため
→フォロー中の文字を非表示にする。
デメリット：他タブとの統一性がなくなる。

個人的には案１でしょうか。

【参考】Twitterの場合は、Person AddとPerson Cancelを使用していました。
![image](https://github.com/aipictors/app/assets/132221228/a4ba3c87-5380-4421-8f03-25e7154307e2)
![image](https://github.com/aipictors/app/assets/132221228/73a5843d-1e36-4c8d-abc2-3f81f0e261af)

**Comment by Stella2211** [comment]
同様の問題は他のタブにも存在するようです。
確かに、フォロー中タブの場合はボタンを隠してしまってもいいとは思いますが、あまりにも投稿者名が長い場合は横のボタンにも被ってしまうので、画像のように、画面に収まりきらない場合は省略するように実装したいと思います。
![long_username_test](https://github.com/aipictors/app/assets/104188098/f92196c1-a3e1-4fb5-b75f-0c162e0137e1)

**Comment by Stella2211** [comment]
フォロー中タブのみの問題であればボタンを隠してもよかったのですが、同様の問題は他のタブにも存在するようです。
また、あまりにも投稿者名が長い場合は横のボタンにも被ってしまうので、画像のように、画面に収まりきらない場合は省略するように実装したいと思います。
![longUserNameTest_ja](https://github.com/aipictors/app/assets/104188098/b0133b66-10a5-482b-a2fb-4131e15e9679)

**Comment by haruharu-1105** [comment]
対応ありがとうございました。
