### ISSUE TITLE
ユーザーをフォロー中のアイコンがハートマークになっており紛らわしい。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#89]
## どのような問題がありますか？
ユーザーをフォロー中のアイコンがハートマークになっており、「いいね」と紛らわしいです。
![image](https://github.com/aipictors/app/assets/132221228/50f29ebb-7f73-4203-8b9d-0489006fded3)

## どうすれば良いですか？
Twitterに合わせて、Person AddとPerson Cancelのアイコンはどうでしょうか？
![image](https://github.com/aipictors/app/assets/132221228/a4ba3c87-5380-4421-8f03-25e7154307e2)
![image](https://github.com/aipictors/app/assets/132221228/73a5843d-1e36-4c8d-abc2-3f81f0e261af)

**Comment by Stella2211** [comment]
画像のように実装しました！
![follow_modal](https://github.com/aipictors/app/assets/104188098/c8fcfd0f-e22e-444a-be69-4a1bc455466f)
![unfollow_modal](https://github.com/aipictors/app/assets/104188098/d9e0de50-37d6-4c7e-a217-c6f8ae9f7d19)

**Comment by haruharu-1105** [comment]
対応　ありがとうございます。
