### ISSUE TITLE
作品画面　アプリとWEBサイトでコメントの内容が一致しない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#95]
## どの機能に関する不具合ですか？

- [x] それ以外　作品画面

## どのような不具合が発生しましたか？

アプリのコメント欄…コメントあり
![image](https://github.com/aipictors/app/assets/132221228/196148f8-25a9-42a4-b206-aa67b5b02fb1)

WEBのコメント欄…コメントなし
![image](https://github.com/aipictors/app/assets/132221228/f25d3d81-51c3-4278-84d5-19467559c789)

## どのような操作をしましたか？

1. 見つける→キーワード検索「へそ出しギャル」を検索
1. 作品ID:57674を表示
https://www.aipictors.com/works/57674/

## どの端末で確認しましたか？

- [x] Android
バージョン: 0.4.1, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せない

**Comment by reiwa** [comment]
@haruharu-1105 修正しました。作品「57674」へのコメントではなく、コメント「57674」へのリプライが混じっていました。

**Comment by haruharu-1105** [comment]
TO @reiwa 
対応ありがとうございます。修正確認しました。
![image](https://github.com/aipictors/app/assets/132221228/ecc6f1e0-22d4-465d-98bc-188d44234d11)

TO @Stella2211 
調査協力、ありがとうございました。
Issueクローズします。
