### ISSUE TITLE
ミュート画面　ミュートしたユーザーを確認する事が出来ない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/app#98]
## どの機能に関する不具合ですか？

- [x] それ以外

## どのような不具合が発生しましたか？

ミュートしたユーザーを確認する事が出来ない。
代わりに自分のアイコンと名前が4件表示されます。
※Webサイトでは、4ユーザーミュートしています。

![image](https://github.com/aipictors/app/assets/132221228/5b1326a8-935e-4215-9d00-83109e7fa8c4)

## どのような操作をしましたか？

1. ログイン状態
1. その他タブ→ミュートしたユーザを表示
1. ログインユーザー（自身）のアイコンが表示されます。

## どの端末で確認しましたか？

- [x] Android
　バージョン: 0.4.1, OS:Android 12, Build:SP1A.210812.016, 端末:A202ZT

## 許せないですか？

- [x] 許せない

**Comment by Stella2211** [comment]
修正しました！
GraphQL側のバグで、ミュート対象のユーザーを返すべきところが、ミュートしたユーザー（自分）を返していることが原因でした。
